### ISSUE TITLE
docker image "agnprz/carbon_sustain" not available

### ISSUE THREAD

**Issue by nmalisa-sb** [HewlettPackard/dc-rl#1]
Hi,

docker image `agnprz/carbon_sustain` could not be found on docker hub or anywhere else using search engines...

Can you publish the Dockerfile for that or offer different solution?

Thank you,
Nikola

**Comment by AvisekNaug** [comment]
Apologies for the late reply but due to some internal company policy we had to remove the docker from GitHub. We suggest users to try out dc-rl with the Python interface (which is well maintained) or if needed try dc-rl with EnergyPlus by building from scratch.
